apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-service
  template:
    metadata:
      labels:
        app: template-service
    spec:
      containers:
      - name: template-service
        image: template-service:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: template-service
spec:
  selector:
    app: template-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
